# See also https://github.com/onk/onkcop/blob/master/config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - bin/**/*

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Max: 32

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 45

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/VariableNumber:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false
