# See also https://github.com/onk/onkcop/blob/master/config/rubocop.yml
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - bin/**/*

Metrics:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RaiseArgs:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

# Configure pending cops

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
